// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinUiClient.Data;

#nullable disable

namespace WinUiClient.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230914092529_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WinUiClient.Data.Bewoner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Job")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Bewoners");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BirthDate = new DateOnly(2002, 12, 3),
                            Job = "idiot",
                            Name = "Name"
                        },
                        new
                        {
                            Id = 2L,
                            BirthDate = new DateOnly(2002, 12, 3),
                            Job = "idiot",
                            Name = "Guy"
                        },
                        new
                        {
                            Id = 3L,
                            BirthDate = new DateOnly(2002, 12, 23),
                            Job = "lol",
                            Name = "Henk"
                        });
                });

            modelBuilder.Entity("WinUiClient.Data.Gebouw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Gebouwen");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Location = "house",
                            Name = "Name",
                            Type = "type"
                        },
                        new
                        {
                            Id = 2L,
                            Location = "Breda",
                            Name = "Curio",
                            Type = "Gevangenis"
                        },
                        new
                        {
                            Id = 3L,
                            Location = "Breda",
                            Name = "Makro",
                            Type = "Loots"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
